AllCops:
  DisplayCopNames: true

  Exclude:
    - 'vendor/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'data/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.3.4

Bundler/OrderedGems:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/For:
  EnforcedStyle: each

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/ExtraSpacing:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingBlankLines:
  EnforcedStyle: final_newline

Style/VariableName:
  EnforcedStyle: snake_case

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/Semicolon:
  AllowAsExpressionSeparator: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AndOr:
  EnforcedStyle: conditionals

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/DotPosition:
  EnforcedStyle: trailing

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/IndentHash:
  EnforcedStyle: consistent

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
